name = "Liam's Modpack 2026"
author = "Liam"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93bb9ae4ab7ff2899eaa5769fdf44030ffed83ef3be730ce80273454041f536d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"

[options]
datapack-folder = "config/paxi/datapacks"
