name = "Liam's Modpack 2026"
author = "Liam"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8645f3af203b4ed21bbb2e9aee496d2af2acf2dd71ac1855e3be88d8c0e282bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"

[options]
datapack-folder = "config/paxi/datapacks"
