name = "Liam's Modpack 2026"
author = "Liam"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3faa16db0ddef7dcd92683dc87ca6d1e8f01db47649fcb511c76e85103637cb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.255"

[options]
datapack-folder = "config/paxi/datapacks"
